import { GraphTemplate } from './GraphTemplateRegistry';
import { GraphSpec } from '@/components/GraphEngine/types';

export class GraphDataPopulationEngine {
    
    /**
     * Takes an AI-generated data payload and merges it with a curated template.
     * Prevents layout hallucination by strictly preserving template properties.
     */
    public static populate(template: GraphTemplate, aiData: any): GraphSpec {
        const spec: GraphSpec = JSON.parse(JSON.stringify(template.baseSpec)); // Deep copy

        // The AI provides dynamic titles or explanations
        if (aiData.title) spec.title = aiData.title;
        if (aiData.explanation) spec.explanation = aiData.explanation;
        if (aiData.axes) {
            if (aiData.axes.x) spec.axes = { ...spec.axes, x: aiData.axes.x };
            if (aiData.axes.y) spec.axes = { ...spec.axes, y: aiData.axes.y };
        }

        // Map AI generated curves strictly into template slots, and append dynamic curves
        if (spec.curves && aiData.curves && Array.isArray(aiData.curves)) {
            const mappedAiIndices = new Set<number>();
            
            spec.curves = spec.curves.map((templateCurve, index) => {
                let aiCurveIndex = aiData.curves.findIndex((c: any) => c.name === templateCurve.name);
                
                // Fallback: If names don't match, map by index
                if (aiCurveIndex === -1 && aiData.curves[index]) {
                    aiCurveIndex = index;
                }

                if (aiCurveIndex !== -1) {
                    mappedAiIndices.add(aiCurveIndex);
                    const aiCurve = aiData.curves[aiCurveIndex];
                    return {
                        ...templateCurve,
                        points: aiCurve.points || templateCurve.points,
                        func: aiCurve.func || templateCurve.func,
                        name: aiCurve.name || templateCurve.name
                    };
                }
                return templateCurve;
            });

            // Append any additional curves generated by the AI (e.g. for comparing multiple datasets)
            const fallbackColors = ['#f43f5e', '#a855f7', '#eab308', '#06b6d4', '#f97316'];
            aiData.curves.forEach((aiCurve: any, index: number) => {
                if (!mappedAiIndices.has(index)) {
                    spec.curves!.push({
                        name: aiCurve.name || `Dataset ${index + 1}`,
                        type: aiCurve.type || spec.curves![0]?.type || 'line',
                        color: aiCurve.color || fallbackColors[index % fallbackColors.length],
                        points: aiCurve.points,
                        func: aiCurve.func
                    });
                }
            });
        }

        return spec;
    }
}
